#ifndef __MX_CERT_EVENT_AGENT__
#define __MX_CERT_EVENT_AGENT__


enum
{
    MX_CERT_EVENT_NOTIFY_ROOTCA_WILL_EXPIRE = 0,
    MX_CERT_EVENT_NOTIFY_ROOTCA_EXPIRE,
    MX_CERT_EVENT_NOTIFY_ENDCERT_WILL_EXPIRE,
    MX_CERT_EVENT_NOTIFY_ENDCERT_EXPIRE,
    MX_CERT_EVENT_NOTIFY_CERT_IMPORTED,
    MX_CERT_EVENT_NOTIFY_CERT_DELETED,    
    MX_CERT_EVENT_NOTIFY_CERT_REGEN
};

int mx_cert_event_notify(int type);

#endif //__MX_CERT_EVENT_AGENT__
