#!/bin/bash
#How to regen rooCA
#Env
#Laputa Docket
#Key
#openssl genrsa --out rootca.key 4096
#Cert
openssl req -new -x509 -key rootca.key -days 3650 -sha256 -extensions v3_ca -out ca.pem -subj /C=TW/ST=Taiwan/L=New Taipei/O=Moxa/CN="Moxa Inc."/emailAddress=taiwan@moxa.com

